### ISSUE TITLE
jar inside standalone console executables did not find assets

### ISSUE THREAD

**Issue by alan-saar** [weavejester/ring-webjars#8]
when using ring-webjars, making a [executable jar](https://skife.org/java/unix/2011/06/20/really_executable_jars.html)
and running, an exception is raised
```java
Caused by: java.lang.NullPointerException
        at org.webjars.urlprotocols.JarUrlProtocolHandler.getAssetPaths(JarUrlProtocolHandler.java:45)
```
The problem is not in ring-webjars, but in the dependency webjars-locator.

webjars-locator 0.34 solve this.

is possible to update ring-webjars webjars-locator dependency 
from org.webjars/webjars-locator  0.27 to version 0.34 ?

**Comment by opqdonut** [comment]
I bumped into this same problem. An uberjar built using boot worked, but one built with deps.edn and depstar needed webjars-locator 0.34 to avoid this NPE.

**Comment by weavejester** [comment]
The dependency has been updated. Apologies for not fixing this sooner - it looks like the issue notifications never arrived in my inbox.
